version: "3.9"

services:
    store:
        image: store:1
        networks:
            - gate
        deploy:
            replicas: 2
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure

    backend:
        image: be:2
        ports:
            - 8080:80
        networks:
            - gate
        depends_on:
            - store
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure

    frontend:
        image: fe:1
        ports:
            - 8081:80
        depends_on:
            - backend
        deploy:
            replicas: 1

networks:
    gate: